packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@bundled-es-modules/glob': false
  core-js: true
  esbuild: true
  style-dictionary: false

# We need this to override old react-router version in peri-v2
overrides:
  '@types/react-router>@types/react': '18.3.31'
  '@types/react-router-dom>@types/react': '18.3.31'
